<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BootstrapValidate" Version="1.4.0" />
    <PackageReference Include="BootstrapValidator" Version="1.0.0" />
    <PackageReference Include="jquery.validate.bootstrap" Version="1.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Baitul_Kitab.BAL\Baitul_Kitab.BAL.csproj" />
    <ProjectReference Include="..\Baitul_Kitab.Data\Baitul_Kitab.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Areas\Category\Data\" />
    <Folder Include="Areas\Category\Models\" />
  </ItemGroup>

</Project>
